### ISSUE TITLE
Use common vulnerability database with bundle-audit

### ISSUE THREAD

**Issue by dzhlobo** [mackuba/holepicker#1]
I watch [bundle-audit](https://github.com/postmodern/bundler-audit) and [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db) projects. I think holepicker can use the ruby-advisory-db as bundle-audit do. It will usefull for both projects. @jsuder what do you think?

**Comment by mackuba** [comment]
Yeah, I saw that, but I found it after I've already finished the first version of holepicker - that's the plan, to use a shared bug database, I just need to figure out the details.

**Comment by grosser** [comment]
Maybe use bundler-audit directly something like [this](https://github.com/grosser/bundler-organization_audit/blob/master/lib/bundler/organization_audit.rb#L33)
