### ISSUE TITLE
HolePicker shouldn't always exit if data file can't be download

### ISSUE THREAD

**Issue by elhu** [mackuba/holepicker#12]
Hi,

I'm using HolePicker as a library, not as a CLI tool, and I came across a behaviour that seems a bit extreme.

If HolePicker can't download the data file, it prints out an error and exits. This behaviour is fine in the context of the command line tool, but isn't when using DatePicker as a library (DatePicker shouldn't cause my program to exit).

I think that if DatePicker::OnlineDatabase fails to download the data file, it should raise an exception, that could then either be handled in bin/holepicker for the CLI tool, or in the Capistrano recipe (probably with an option to decide whether to exit or not), or in any arbitrary code using HolePicker as a library.

If you think this feature could be useful, please let me know and I'll be happy to provide a pull-request!

**Comment by mackuba** [comment]
Yeah, you're right, an exception makes more sense. I'm on vacation now, but you can send me a pull request and I'll merge it later.
