### ISSUE TITLE
looking for a new maintainer

### ISSUE THREAD

**Issue by mackuba** [mackuba/holepicker#21]
Last year I decided to leave the webdev world and concentrate only on Cocoa development. I still love Ruby as a language (especially as compared to ObjC - Swift is much better though), but it was just too much effort to try to keep up with Ruby, JS and Cocoa all the time, and I had to choose something.

I haven't been up to date with all the latest developments in the Ruby world since then, I'm not even sure which version of Ruby is the latest stable one now (2.1 I think?). I've been updating the Holepicker data file whenever I see tweets about a new Rails release with security fixes, and I've fixed the Rainbow bug, but I'm not willing to put any more effort than that into this project, since I have other projects to maintain too.

So I'm thinking that it would be better both for me and for users if this tool was taken over by someone who is still using Ruby daily and can take a better care of it. Anyone interested?

cc @cbeer @manuelvanrijn @xiazek @bct @timpeters @pascalvanhecke @elhu @spk @ghost @lasseebert @AlexMC @adelevie

**Comment by lasseebert** [comment]
I'm not actively using holepicker myself anymore (still thinks it's a great gem!), so I might not be the right candidate.

If no one else applies, I will reconsider ;)

**Comment by lasseebert** [comment]
Great job building this, btw :+1:

**Comment by cbeer** [comment]
Thanks @jsuder. We're still using holepicker, but I think we can migrate to [rubysec/bundler-audit](https://github.com/rubysec/bundler-audit) and be about as happy. Again, thanks for your work.

**Comment by spk** [comment]
Hello, I'm also not using holepicker right now, so I don't think I will be a good maintainer, but thanks for your proposition @jsuder !

**Comment by manuelvanrijn** [comment]
Hi, same for me, not using it right now. Thanks for your hard work

**Comment by mcgoooo** [comment]
Thanks for the hard work first of all. 

Just a note though, can you please use deprecation warnings next time you need to deprecate a gem, at least for a few weeks. Heroku sporadically restarts it's system, which using this methodology caused all forms of hassle, crashing our production systems to crash

**Comment by mackuba** [comment]
Sorry about that :( Unfortunately I hadn't built in any more graceful deprecation mechanism earlier, so I couldn't notify existing users any other way, I could only release an updated version, but only a fraction of users would update to the new version in the next few weeks. The only options I had if I didn't want to keep the data file up to date was either to pretend everything is fine, or just make it obvious that it isn't...

**Comment by akshatpradhan** [comment]
I think its important to note in the title of this repository that you recommend `bundler-audit`. I'm using it now and its pretty good.
